//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Working_Org.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_account_balance_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_account_balance_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_account_balance_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_account_balance_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_back_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_back_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_back_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_back_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_downward_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_downward_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_downward_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_downward_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_forward_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_forward_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_forward_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_forward_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_upward_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_upward_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_upward_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_upward_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assignment_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assignment_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assignment_late_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_late_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assignment_late_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_late_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assignment_turned_in_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_turned_in_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assignment_turned_in_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_assignment_turned_in_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assistant_photo_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_assistant_photo_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_assistant_photo_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_assistant_photo_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_chat_bubble_outline_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_chat_bubble_outline_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_chat_bubble_outline_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_chat_bubble_outline_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_chevron_left_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_chevron_left_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_chevron_left_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_chevron_left_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_chevron_right_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_chevron_right_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_chevron_right_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_chevron_right_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_control_point_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_control_point_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_control_point_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_control_point_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_delete_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_delete_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete_forever_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_delete_forever_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete_forever_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_delete_forever_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete_sweep_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_delete_sweep_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete_sweep_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_delete_sweep_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_description_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_description_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_description_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_description_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_expand_less_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_expand_less_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_expand_less_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_expand_less_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_fast_forward_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_fast_forward_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_fast_forward_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_fast_forward_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_fast_rewind_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_fast_rewind_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_fast_rewind_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_fast_rewind_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_feedback_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_feedback_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_feedback_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_feedback_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_first_page_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_first_page_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_first_page_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_first_page_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_folder_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_folder_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_folder_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_folder_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_forward_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_forward_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_forward_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_forward_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_group_work_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_group_work_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_group_work_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_group_work_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_home_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_home_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_home_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_home_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_info_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_info_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_info_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_info_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_info_outline_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_info_outline_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_info_outline_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_info_outline_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_last_page_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_last_page_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_last_page_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_last_page_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_list_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_list_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_list_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_list_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_lock_open_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_lock_open_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_lock_open_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_lock_open_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_lock_outline_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_lock_outline_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_lock_outline_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_lock_outline_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_menu_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_menu_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_menu_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_menu_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_mode_edit_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_mode_edit_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_mode_edit_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_mode_edit_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_person_add_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_person_add_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_person_add_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_person_add_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_person_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_person_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_person_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_person_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_person_outline_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_person_outline_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_person_outline_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_person_outline_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_poll_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_poll_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_poll_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_poll_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_public_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_public_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_public_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_public_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_remove_circle_outline_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_remove_circle_outline_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_remove_circle_outline_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_remove_circle_outline_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_report_problem_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_report_problem_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_report_problem_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_report_problem_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_search_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_search_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_search_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_search_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_send_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_send_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_send_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_send_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_settings_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_settings_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_settings_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_settings_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_skip_next_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_skip_next_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_skip_next_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_skip_next_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_skip_previous_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_skip_previous_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_skip_previous_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_skip_previous_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_star_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_star_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_star_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_star_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_star_border_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_star_border_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_star_border_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_star_border_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_store_black_24dp_1x {
            get {
                object obj = ResourceManager.GetObject("ic_store_black_24dp_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_store_black_24dp_2x {
            get {
                object obj = ResourceManager.GetObject("ic_store_black_24dp_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_Add1x {
            get {
                object obj = ResourceManager.GetObject("Pic_Add1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_Add2x {
            get {
                object obj = ResourceManager.GetObject("Pic_Add2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_Clear1x {
            get {
                object obj = ResourceManager.GetObject("Pic_Clear1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_Clear2x {
            get {
                object obj = ResourceManager.GetObject("Pic_Clear2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_Save1x {
            get {
                object obj = ResourceManager.GetObject("Pic_Save1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pic_Save2x {
            get {
                object obj = ResourceManager.GetObject("Pic_Save2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sUserPath {
            get {
                return ResourceManager.GetString("sUserPath", resourceCulture);
            }
        }
    }
}
