//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public long Id { get; set; }
        public string Numero { get; set; }
        public string Banco { get; set; }
        public string Tipo { get; set; }
        public string FechaEmision { get; set; }
        public string FechaCobro { get; set; }
        public long IdCliente { get; set; }
        public decimal Monto { get; set; }
        public string Ubicacion { get; set; }
        public string Observaciones { get; set; }
    }
}
