//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaFactura
    {
        public long Id { get; set; }
        public long IdFactura { get; set; }
        public long IdProducto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Subtotal { get; set; }
        public decimal AlicuotaIva { get; set; }
        public decimal Total { get; set; }
        public string Estado { get; set; }
        public decimal Iva { get; set; }
    }
}
