//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public long Id { get; set; }
        public long IdProducto { get; set; }
        public string Fecha { get; set; }
        public string FechaElaboracion { get; set; }
        public string FechaVencimiento { get; set; }
        public string NumeroLote { get; set; }
        public decimal Cantidad { get; set; }
        public string Observaciones { get; set; }
    }
}
