//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public long OC { get; set; }
        public long CD { get; set; }
        public string FechaEmision { get; set; }
        public string FechaEntrega { get; set; }
        public string HoraEntrega { get; set; }
        public string MuelleEntrega { get; set; }
        public long Reprogramaciones { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public decimal Total { get; set; }
        public decimal Pendiente { get; set; }
    }
}
