//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string UnidadDeMedida { get; set; }
        public string TipoProducto { get; set; }
        public string Ean13 { get; set; }
        public long VidaUtil { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoNeto { get; set; }
        public decimal UnidadesBulto { get; set; }
        public decimal PesoBulto { get; set; }
        public decimal StockMinimo { get; set; }
        public decimal StockMaximo { get; set; }
        public decimal StockOptimo { get; set; }
    }
}
