//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoProveedor
    {
        public long Id { get; set; }
        public long IdProducto { get; set; }
        public long IdProveedor { get; set; }
        public long DemoraPromedio { get; set; }
        public string Observaciones { get; set; }
    }
}
