//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proveedorEntities : DbContext
    {
        public proveedorEntities()
            : base("name=proveedorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Lote> Lotes { get; set; }
        public virtual DbSet<MovimientoProducto> MovimientoProductoes { get; set; }
        public virtual DbSet<Pedido> Pedidoes { get; set; }
        public virtual DbSet<PrecioProducto> PrecioProductoes { get; set; }
        public virtual DbSet<ProduccionDiaria> ProduccionDiarias { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<Cheque> Cheques { get; set; }
        public virtual DbSet<Cobranza> Cobranzas { get; set; }
        public virtual DbSet<LineaCobranza> LineaCobranzas { get; set; }
        public virtual DbSet<LineaVenta> LineaVentas { get; set; }
        public virtual DbSet<ProductoProveedor> ProductoProveedors { get; set; }
        public virtual DbSet<DetalleListaFabricacion> DetalleListaFabricacions { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<LineaFactura> LineaFacturas { get; set; }
        public virtual DbSet<LineaOrdenDeCompra> LineaOrdenDeCompras { get; set; }
        public virtual DbSet<ListaFabricacion> ListaFabricacions { get; set; }
        public virtual DbSet<OrdenDeCompra> OrdenDeCompras { get; set; }
        public virtual DbSet<Remito> Remitoes { get; set; }
        public virtual DbSet<LineaRemito> LineaRemitoes { get; set; }
        public virtual DbSet<MovimientoProveedor> MovimientoProveedors { get; set; }
        public virtual DbSet<Retencion> Retencions { get; set; }
        public virtual DbSet<MovimientoCliente> MovimientoClientes { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
        public virtual DbSet<LineaPedido> LineaPedidoes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
    }
}
