//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public long Id { get; set; }
        public string EmisionRecepcion { get; set; }
        public long IdEmisor { get; set; }
        public long IdDestinatario { get; set; }
        public string FechaEmision { get; set; }
        public string FechaEntrega { get; set; }
        public string Numero { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    }
}
