//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retencion
    {
        public long Id { get; set; }
        public string Tipo { get; set; }
        public string NumDocumento { get; set; }
        public decimal Base { get; set; }
        public decimal Alicuota { get; set; }
        public decimal Total { get; set; }
        public string Fecha { get; set; }
        public long IdCobranza { get; set; }
    }
}
