//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos
    {
        public long Id { get; set; }
        public string Clasificacion { get; set; }
        public string Nombre { get; set; }
        public string Detalle { get; set; }
    }
}
