//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Working_Org
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public string Fecha { get; set; }
        public string Documento { get; set; }
        public string DocumentoNro { get; set; }
        public long IdPedido { get; set; }
        public decimal Monto { get; set; }
        public decimal MontoTotal { get; set; }
        public string Estado { get; set; }
    }
}
